name: Deploy to Production 1

on:
  push:
    branches: [ main ]

jobs:

  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy in EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
              host: ${{ secrets.HOST_NAME  }}
              username: ${{ secrets.USER_NAME  }}
              key: ${{ secrets.AWS_PRIVATE_KEY  }}
              port: ${{ secrets.PORT }}
              script: |
               whoami
               cd stack/wordpress/wp-content/themes/wordpress-gcr-theme/
               ls -la
               git pull
               git status
            
